int led = 7;
int buzzer = 4;
int l = 1;


void setup(){
    pinMode(led, OUTPUT);
    pinMode(buzzer, OUTPUT);
}

void loop() {
  if (l==1){
  digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(7*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(7*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(7*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(3*50);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(3*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    digitalWrite(led, HIGH);
    digitalWrite(buzzer, HIGH);
    delay(1*50);
    digitalWrite(led, LOW);
    digitalWrite(buzzer, LOW);
    delay(7*50);
    l++;
  }
  else{
    digitalWrite(led, LOW);
  }
}

